check setting git
VPanadiy/Cake pull request #5
Opened 2017-09-04 12:03 UTC by DazzlingSasha

2017-10-27 15:41 UTC, VPanadiy approved these changes

2017-10-30 14:10 UTC, DazzlingSasha reviewed
update repository

2017-10-30 14:15 UTC, VPanadiy requested changes
test

2017-10-30 14:16 UTC, VPanadiy approved these changes

2017-10-30 14:28 UTC, VPanadiy approved these changes

2017-10-30 14:32 UTC, merged